# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:07
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='facebook_ratio',
            field=image_cropping.fields.ImageRatioField('image', '1200x628', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='facebook ratio'),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='pinterest_ratio',
            field=image_cropping.fields.ImageRatioField('image', '1102x735', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='pinterest ratio'),
        ),
    ]
