# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 21:29
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snote', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='short_text',
            field=redactor.fields.RedactorField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
