# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 21:31
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snote', '0003_note_short_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='short_text',
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=redactor.fields.RedactorField(blank=True, null=True),
        ),
    ]
